### ISSUE TITLE
Monster AI

### ISSUE THREAD

**Issue by MagLuTiLa** [MagLuTiLa/Rooms-of-doom#14]
Het gedrag van de monster zou wat kunnen worden aangepast. No rocket science here, gewoon wat variatie naast het bullrushen wat ze nu allemaal doen.

**Comment by MagLuTiLa** [comment]
Vluchtende monsters vallen de speler aan als de speler in de weg staat, in plaats van door de speler heen te lopen.

**Comment by Samonum** [comment]
AI occasionally takes some time to consider it's next move.
